disabled_rules:
  - private_over_fileprivate
  - closure_parameter_position
  - opening_brace
  - large_tuple

opt_in_rules:
  - contains_over_first_not_nil
  - convenience_type
  - cyclomatic_complexity
  - discouraged_object_literal
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - identical_operands
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - redundant_type_annotation
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_declaration 
  - vertical_whitespace_opening_braces

included:
  - HackerNews
  - Api
  - ApiTests
  - Domain
  - Platform
  - PlatformTests
  - iOS
  - iOSTests

line_length:
  - 100
  - 200

function_body_length:
  - 50
  - 100

identifier_name:
  min_length: 1
  max_length: 40

cyclomatic_complexity:
  ignores_case_statements: true

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

trailing_comma:
    mandatory_comma: true
